import { Question } from "./types";

// Extracted questions from the uploaded CBSE Science Question Paper
export const CBSE_SCIENCE_QUESTIONS: Question[] = [
  {
    id: "1",
    displayNumber: "1",
    text: "The metals obtained from their molten chlorides by the process of electrolytic reduction are : (A) Gold and silver (B) Calcium and magnesium (C) Aluminium and silver (D) Sodium and iron",
    maxMarks: 1,
    order: 1,
  },
  {
    id: "2",
    displayNumber: "2",
    text: "The formation of magnesium oxide is correctly shown in option :",
    maxMarks: 1,
    order: 2,
  },
  {
    id: "3",
    displayNumber: "3",
    text: "Reaction between two elements A and B, forms a compound C. A loses electrons and B gains electrons. Which one of the following properties will not be shown by compound C ? (A) It has high melting point (B) It is highly soluble in water (C) It has weak electrostatic forces (D) It conducts electricity in molten state",
    maxMarks: 1,
    order: 3,
  },
  {
    id: "4",
    displayNumber: "4",
    text: "Consider the following reactions: (i) Dilute hydrochloric acid reacts with sodium hydroxide (ii) Magnesium oxide reacts with dilute hydrochloric acid (iii) Carbon dioxide reacts with sodium hydroxide. In each case: (A) Salt and water is formed (B) Neutral salts are formed (C) Hydrogen gas is formed (D) Acidic salts are formed",
    maxMarks: 1,
    order: 4,
  },
  {
    id: "5",
    displayNumber: "5",
    text: "Tooth enamel is made up of calcium hydroxyapatite (a crystalline form of calcium phosphate). This chemical starts corroding in the mouth when the pH is : (A) 7 (B) 5 (C) 10 (D) 14",
    maxMarks: 1,
    order: 5,
  },
  {
    id: "6",
    displayNumber: "6",
    text: "The products formed when Aluminium and Magnesium are burnt in the presence of air respectively are : (A) Al3O4 and MgO2 (B) Al2O3 and MgO (C) Al3O4 and MgO (D) Al2O3 and MgO2",
    maxMarks: 1,
    order: 6,
  },
  {
    id: "7",
    displayNumber: "7",
    text: "Electrolysis of water is a decomposition reaction. The mass ratio (MH : MO) of hydrogen and oxygen gases liberated at the electrodes during electrolysis of water is : (A) 8:1 (B) 2:1 (C) 1:2 (D) 1:8",
    maxMarks: 1,
    order: 7,
  },
  {
    id: "8",
    displayNumber: "8",
    text: "The breakdown of glucose has taken the following pathway: Glucose -> Pyruvate -> Lactic acid + Energy. The sites 'a' and 'b' respectively are : (A) Mitochondria and Oxygen deficient muscle cells (B) Cytoplasm and Oxygen rich muscle cells (C) Cytoplasm and Yeast cells (D) Cytoplasm and Oxygen deficient muscle cells",
    maxMarks: 1,
    order: 8,
  },
  {
    id: "9",
    displayNumber: "9",
    text: "If pea plants with round and green seeds (RRyy) are crossed with pea plants having wrinkled and yellow seeds (rrYY), the seeds developed by the plants of F1 generation will be : (A) 50% round and green (B) 75% wrinkled and green (C) 100% round and yellow (D) 75% wrinkled and yellow",
    maxMarks: 1,
    order: 9,
  },
  {
    id: "10",
    displayNumber: "10",
    text: "The correct/true statement(s) for a bisexual flower is/are: (i) They possess both stamen and pistil (ii) They possess either stamen or pistil (iii) They exhibit either self-pollination or cross-pollination (iv) They cannot produce fruits on their own. (A) (i) only (B) (iv) only (C) (i) and (iii) (D) (i) and (iv)",
    maxMarks: 1,
    order: 10,
  },
  {
    id: "11",
    displayNumber: "11",
    text: "The plant hormone whose concentration stimulates the cells to grow longer on the side of the shoot which is away from light is : (A) Cytokinins (B) Gibberellins (C) Adrenaline (D) Auxins",
    maxMarks: 1,
    order: 11,
  },
  {
    id: "12",
    displayNumber: "12",
    text: "Secretion of less saliva in mouth will effect the conversion of : (A) proteins into amino acids (B) fats into fatty acids and glycerol (C) starch into simple sugars (D) sugars into alcohol",
    maxMarks: 1,
    order: 12,
  },
  {
    id: "13",
    displayNumber: "13",
    text: "The percentage of solar energy which is not converted into food energy by the leaves of green plants in a terrestrial ecosystem is about : (A) 1% (B) 10% (C) 90% (D) 99%",
    maxMarks: 1,
    order: 13,
  },
  {
    id: "14",
    displayNumber: "14",
    text: "Which of the following groups do not constitute a food chain ? (i) Wolf, rabbit, grass, lion (ii) Plankton, man, grasshopper, fish (iii) Hawk, grass, snake, grasshopper, frog (iv) Grass, snake, wolf, tiger. (A) (i) and (iv) (B) (i) and (iii) (C) (ii) and (iii) (D) (ii) and (iv)",
    maxMarks: 1,
    order: 14,
  },
  {
    id: "15",
    displayNumber: "15",
    text: "The phenomenon responsible for making the smoke particles visible when a beam of sunlight enters a smoke filled room through a narrow hole is : (A) scattering of light (B) dispersion of light (C) reflection of light (D) internal reflection of light",
    maxMarks: 1,
    order: 15,
  },
  {
    id: "16",
    displayNumber: "16",
    text: "Mirror 'X' is used to concentrate sunlight in solar furnace and Mirror 'Y' is fitted on the side of the vehicle to see the traffic behind the driver. (A) (i) and (ii) (B) (ii) and (iii) (C) (iii) and (iv) (D) (i) and (iv)",
    maxMarks: 1,
    order: 16,
  },
  {
    id: "17",
    displayNumber: "17",
    text: "Assertion (A) : The amount of ozone in the atmosphere began to drop sharply in the 1980s. Reason (R) : The oxygen atoms combine with molecular oxygen to form ozone.",
    maxMarks: 1,
    order: 17,
  },
  {
    id: "18",
    displayNumber: "18",
    text: "Assertion (A) : No two magnetic field lines are found to cross each other. Reason (R) : The compass needle cannot point towards two directions at the point of intersection.",
    maxMarks: 1,
    order: 18,
  },
  {
    id: "19",
    displayNumber: "19",
    text: "Assertion (A) : A human child bears all the basic features of human beings. Reason (R) : It looks exactly like its parents, showing very little variations.",
    maxMarks: 1,
    order: 19,
  },
  {
    id: "20",
    displayNumber: "20",
    text: "Assertion (A) : Decomposition reactions are generally endothermic reactions. Reason (R) : Decomposition of organic matter into compost is an exothermic process.",
    maxMarks: 1,
    order: 20,
  },
  {
    id: "21",
    displayNumber: "21",
    text: "An object is placed at a distance of 10 cm in front of a concave mirror of focal length 15 cm. Use mirror formula to determine the position of the image formed by this mirror.",
    maxMarks: 2,
    order: 21,
  },
  {
    id: "22a",
    displayNumber: "22",
    subLabel: "a.",
    text: "Consider two lamps A and B of rating 50 W; 220 V and 25 W; 220 V respectively. Find the ratio of the resistances of the two lamps (i.e. RA : RB).",
    maxMarks: 2,
    order: 22,
  },
  {
    id: "22b",
    displayNumber: "22",
    subLabel: "b.",
    text: "OR: Heat produced per second due to a current in a resistor of 4 Ω is 400 joules. Calculate the potential difference across the resistor.",
    maxMarks: 2,
    order: 23,
  },
  {
    id: "23",
    displayNumber: "23",
    text: "Draw labelled diagrams to show different stages of budding in Hydra.",
    maxMarks: 2,
    order: 24,
  },
  {
    id: "24a",
    displayNumber: "24",
    subLabel: "a.",
    text: "Besides minimising the loss of blood, why is it essential to plug any leak in a blood vessel ? Name the component of blood which helps in this process and state how this component perform this function.",
    maxMarks: 2,
    order: 25,
  },
  {
    id: "24b",
    displayNumber: "24",
    subLabel: "b.",
    text: "OR: (i) The transport system in plants is relatively slower than in animals. Give reasons. (ii) State the role of phloem in the transport of materials in plants.",
    maxMarks: 2,
    order: 26,
  },
  {
    id: "25",
    displayNumber: "25",
    text: "A student performs the following experiment in his school laboratory. List two observations to justify that in this experiment a chemical change has taken place.",
    maxMarks: 2,
    order: 27,
  },
  {
    id: "26a",
    displayNumber: "26",
    subLabel: "a.",
    text: "Translate into chemical equation and balance: Nitric acid reacts with calcium hydroxide to form calcium nitrate and water.",
    maxMarks: 2,
    order: 28,
  },
  {
    id: "26b",
    displayNumber: "26",
    subLabel: "b.",
    text: "Translate into chemical equation and balance: Sodium chloride reacts with silver nitrate to form silver chloride and sodium nitrate.",
    maxMarks: 2,
    order: 29,
  },
  {
    id: "27a",
    displayNumber: "27",
    subLabel: "a.",
    text: "Define one volt potential difference between two points in an electric field.",
    maxMarks: 1,
    order: 30,
  },
  {
    id: "27b",
    displayNumber: "27",
    subLabel: "b.",
    text: "Draw a schematic diagram of an electric circuit of a cell of 1.5 V, 5 Ω and 10 Ω resistor and a plug key in series. Calculate current.",
    maxMarks: 2,
    order: 31,
  },
  {
    id: "28a",
    displayNumber: "28",
    subLabel: "a.",
    text: "Calculate total resistance of the circuit with parallel combination.",
    maxMarks: 1,
    order: 32,
  },
  {
    id: "28b",
    displayNumber: "28",
    subLabel: "b.",
    text: "Calculate total current drawn from the source.",
    maxMarks: 1,
    order: 33,
  },
  {
    id: "28c",
    displayNumber: "28",
    subLabel: "c.",
    text: "Calculate potential difference across parallel combination of 10 Ω and 15 Ω resistors.",
    maxMarks: 1,
    order: 34,
  },
  {
    id: "29",
    displayNumber: "29",
    text: "Draw ray diagrams to show the nature, position and relative size of the image formed by a convex mirror when the object is placed (i) at infinity and (ii) between infinity and pole P of the mirror.",
    maxMarks: 3,
    order: 35,
  },
  {
    id: "30a",
    displayNumber: "30",
    subLabel: "a.",
    text: "How many chromosomes are present in human beings ? Out of these how many are sex chromosomes ?",
    maxMarks: 1,
    order: 36,
  },
  {
    id: "30b",
    displayNumber: "30",
    subLabel: "b.",
    text: "Explain how, in sexually reproducing organisms, the number of chromosomes in the progeny is maintained.",
    maxMarks: 2,
    order: 37,
  },
  {
    id: "31a",
    displayNumber: "31",
    subLabel: "a.",
    text: "A hormone 'X' is secreted in blood when a person is under scary situation. Identify the hormone 'X' and the gland that secretes it.",
    maxMarks: 1,
    order: 38,
  },
  {
    id: "31b",
    displayNumber: "31",
    subLabel: "b.",
    text: "Explain the role of hormone 'X' (Adrenaline) in dealing with scary or emergency situations.",
    maxMarks: 2,
    order: 39,
  },
  {
    id: "32a",
    displayNumber: "32",
    subLabel: "a.",
    text: "With the help of an activity, explain the conditions under which iron articles get rusted.",
    maxMarks: 3,
    order: 40,
  },
  {
    id: "33a",
    displayNumber: "33",
    subLabel: "a.",
    text: "Displacement reactions also play a key role in extracting metals in the middle of the reactivity series. Justify with two examples.",
    maxMarks: 2,
    order: 41,
  },
  {
    id: "33b",
    displayNumber: "33",
    subLabel: "b.",
    text: "Why can metals high up in the reactivity series not be obtained by reduction of their oxides by carbon ?",
    maxMarks: 1,
    order: 42,
  },
  {
    id: "34a",
    displayNumber: "34",
    subLabel: "a.",
    text: "(i) The power of a lens 'X' is -2.5 D. Name the lens and determine its focal length. For which eye defect is it prescribed ? (ii) Value of magnification 'm' is -2. State nature, size, position, sign of height. (iii) Higher convergence/divergence for 10 cm vs 20 cm focal length.",
    maxMarks: 5,
    order: 43,
  },
  {
    id: "35a",
    displayNumber: "35",
    subLabel: "a.",
    text: "(i) Write functions of: (I) Ovary (II) Fallopian tube (III) Uterus. (ii) State two contraceptive methods used by human males.",
    maxMarks: 5,
    order: 44,
  },
  {
    id: "36a",
    displayNumber: "36",
    subLabel: "a.",
    text: "(i) Draw electron dot structure of chlorine molecule. (ii) Chlorine reaction with methane in sunlight. (iii) Two oxidising agents for alcohol to acid. (iv) Four differences between covalent and ionic compounds.",
    maxMarks: 5,
    order: 45,
  },
  {
    id: "37a",
    displayNumber: "37",
    subLabel: "a.",
    text: "Case Study Electric Power: (a) Write the colours of the insulation covers of the line wires through which supply comes to our homes.",
    maxMarks: 1,
    order: 46,
  },
  {
    id: "37b",
    displayNumber: "37",
    subLabel: "b.",
    text: "Case Study: (b) What should be the current rating of the electric circuit (220 V) so that an electric iron of 1 kW power rating can be operated ?",
    maxMarks: 1,
    order: 47,
  },
  {
    id: "37c",
    displayNumber: "37",
    subLabel: "c.",
    text: "Case Study: (c) What is the function of the earth wire ? State advantage in domestic appliances.",
    maxMarks: 2,
    order: 48,
  },
  {
    id: "38a",
    displayNumber: "38",
    subLabel: "a.",
    text: "Case Study Salts: (a) Write balanced chemical equations to show products formed during electrolysis of brine.",
    maxMarks: 1,
    order: 49,
  },
  {
    id: "38b",
    displayNumber: "38",
    subLabel: "b.",
    text: "Case Study: (b) List two uses of any one product obtained during electrolysis of brine.",
    maxMarks: 1,
    order: 50,
  },
  {
    id: "38c",
    displayNumber: "38",
    subLabel: "c.",
    text: "Case Study: (c) Salt 'A' used for faster cooking is heated to produce 'B' for removing water hardness. Identify A and B and write equation.",
    maxMarks: 2,
    order: 51,
  },
  {
    id: "39a",
    displayNumber: "39",
    subLabel: "a.",
    text: "Case Study Life Processes: (a) Name and define the process by which green plants prepare food.",
    maxMarks: 1,
    order: 52,
  },
  {
    id: "39b",
    displayNumber: "39",
    subLabel: "b.",
    text: "Case Study: (b) Write chemical equation involved in photosynthesis.",
    maxMarks: 1,
    order: 53,
  },
  {
    id: "39c",
    displayNumber: "39",
    subLabel: "c.",
    text: "Case Study: (c) State sequence of events in food synthesis by desert plants OR effect of cloudy weather and dust on rate.",
    maxMarks: 2,
    order: 54,
  },
];
